name: notification_test
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_messaging: ^15.2.0
  firebase_core: ^3.10.0
  flutter_local_notifications: ^18.0.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  freezed_annotation: ^2.4.4
  reactive_forms: ^17.0.1

  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.7
  build_runner: 2.4.11
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


